sudo: false

language: php
php:
  - 7.0
  - 7.1

matrix:
    include:
        - php: 7.0
          env: dependencies=lowest

before_script:
  - composer install --no-interaction -o
  - if [ "$dependencies" = "lowest" ]; then composer update -o --prefer-lowest; fi;

script:
  - mkdir -p build/logs
  - bin/phpunit

after_script:
  - bin/coveralls -v
