language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - curl --version
  - composer install --no-interaction --prefer-source --dev
  - ~/.nvm/nvm.sh install v0.6.14
  - ~/.nvm/nvm.sh run v0.6.14
  - if [[ "$TRAVIS_PHP_VERSION" != "7.0" || "$TRAVIS_PHP_VERSION" != "7.1" ]]; then echo "xdebug.overload_var_dump = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini || true; fi

script: make test

matrix:
  allow_failures:
    - php: hhvm
      dist: trusty
    - php: nightly
  include:
    - php: hhvm
      dist: trusty
  fast_finish: true